"""empty message

Revision ID: 368da79903cf
Revises: e81d9286413f
Create Date: 2024-12-20 21:25:07.243315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368da79903cf'
down_revision = 'e81d9286413f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    # ### end Alembic commands ###
